about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about_page, name='about'),
]

dating_app/urls.py
from django.contrib import admin
from django.urls import path, include
from profiles.views import signup_view , my_profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('', include("profiles.urls") , name='profiles.urls'),
    path('custom-signup/', signup_view, name='custom_signup'),
    path('my-profile/', my_profile, name='my_profile'),
    path('about/', include('about.urls')),
    path('messaging/', include(('messaging.urls', 'messaging'), namespace='messaging')),
]

messaging/urls.py
from django.urls import path
from . import views

app_name = 'messaging'

urlpatterns = [
    path('matches/', views.match_list, name='match_list'),  # List of matches
    path('chat/<str:username>/', views.chat_view, name='chat'),  # Individual chat view
    path('chat/<str:username>/get_new_messages/', views.get_new_messages, name='get_new_messages'),

]

messaging/models.py
from django.db import models
from profiles.models import UserProfile

class Message(models.Model):
    sender = models.ForeignKey(
        UserProfile, 
        related_name='messaging_messages_sent', 
        on_delete=models.CASCADE
    )
    receiver = models.ForeignKey(
        UserProfile, 
        related_name='messaging_messages_received', 
        on_delete=models.CASCADE
    )
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"Message from {self.sender.username} to {self.receiver.username}"

    class Meta:
        ordering = ['timestamp']

messaging/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from profiles.models import UserProfile,Match
from django.contrib.auth.decorators import login_required
from .models import Message
from django.http import JsonResponse

@login_required
def match_list(request):
    # Get the current user's profile
    user_profile = UserProfile.objects.get(username=request.user.username)

    # Find matches where the current user is either user1 or user2
    matches = Match.objects.filter(Q(user1=user_profile) | Q(user2=user_profile))

    # Extract the user profiles from these matches
    matched_profiles = []
    for match in matches:
        if match.user1 != user_profile:
            matched_profiles.append(match.user1)
        else:
            matched_profiles.append(match.user2)

    return render(request, 'messaging/match_list.html', {'matched_profiles': matched_profiles})


@login_required
def chat_view(request, username):
    try:
        other_user = UserProfile.objects.get(username=username)
    except UserProfile.DoesNotExist:
        return redirect('messaging:match_list')

    if request.method == 'POST':
        content = request.POST.get('content')
        if content:
            # Use request.user directly since it's already an instance of UserProfile
            Message.objects.create(sender=request.user, receiver=other_user, content=content)
            return redirect('messaging:chat', username=username)

    chat_messages = Message.objects.filter(
        Q(sender=request.user, receiver=other_user) |
        Q(sender=other_user, receiver=request.user)
    ).order_by('timestamp')

    return render(request, 'messaging/chat.html', {'other_user': other_user, 'chat_messages': chat_messages})


@login_required
def get_new_messages(request, username):
    try:
        other_user = UserProfile.objects.get(username=username)
    except UserProfile.DoesNotExist:
        return JsonResponse({'error': 'User not found'}, status=404)

    last_message_id = request.GET.get('last_message_id', 0)
    try:
        last_message_id = int(last_message_id)
    except ValueError:
        last_message_id = 0

    new_messages = Message.objects.filter(
        Q(sender=request.user, receiver=other_user) | Q(sender=other_user, receiver=request.user),
        id__gt=last_message_id
    ).order_by('timestamp')


    chat_messages_data = [{
        'id': message.id,
        'sender': message.sender.username,
        'content': message.content,
        'timestamp': message.timestamp.strftime('%Y-%m-%d %H:%M:%S')
    } for message in new_messages]

    return JsonResponse({'chat_messages': chat_messages_data})

messaging/templates/messaging/chat.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container chat-container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center mb-4">Chat with {{ other_user.username }}</h1>

                    <div class="message-history mb-4">
                        {% if chat_messages %}
                        {% for message in chat_messages %}
                        <div class="mb-2 {% if message.sender == request.user %}text-end{% else %}text-start{% endif %}" data-message-id="{{ message.id }}">
                            <span class="message-bubble {% if message.sender == request.user %}user-message{% else %}other-user-message{% endif %}">
                                {{ message.content }}
                            </span>
                        </div>
                        {% endfor %}
                        {% else %}
                        <p class="text-center text-muted">No messages received yet.</p>
                        {% endif %}
                    </div>

                    <form method="post" class="mb-3">
                        {% csrf_token %}
                        <div class="mb-3">
                            <textarea name="content" class="form-control" rows="3" placeholder="Type your message here..."></textarea>
                        </div>
                        <div class="text-end">
                            <button type="submit" class="btn btn-login-logout">Send</button>
                        </div>
                    </form>

                    <div class="text-center">
                        <a href="{% url 'messaging:match_list' %}" class="link">Back to Matches</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">
    const currentUserUsername = "{{ request.user.username }}";
    const getNewMessagesUrl = "{% url 'messaging:get_new_messages' other_user.username %}";
</script>

<script src="{% static 'js/checkforNewMessages.js' %}"></script>
{% endblock %}

messaging/templates/messaging/match_list.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center mb-4">Matches</h1>
                    {% if matched_profiles %}
                    <ul class="list-group">
                        {% for profile in matched_profiles %}
                        <li class="list-group-item">
                            <a class="pink-link" href="{% url 'messaging:chat' profile.username %}">
                                {{ profile.username }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <p class="text-center">No matches yet.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}