about/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.about_page, name='about'),
]

dating_app/urls.py
from django.contrib import admin
from django.urls import path, include
from profiles.views import signup_view , my_profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('', include("profiles.urls") , name='profiles.urls'),
    path('custom-signup/', signup_view, name='custom_signup'),
    path('my-profile/', my_profile, name='my_profile'),
    path('about/', include('about.urls')),
    path('messaging/', include(('messaging.urls', 'messaging'), namespace='messaging')),
]

messaging/urls.py
from django.urls import path
from . import views

app_name = 'messaging'

urlpatterns = [
    path('matches/', views.match_list, name='match_list'),  # List of matches
    path('chat/<str:username>/', views.chat_view, name='chat'),  # Individual chat view
    path('chat/<str:username>/get_new_messages/', views.get_new_messages, name='get_new_messages'),

]

templates/base.html
{% load static %}
{% url 'home' as home_url %}
{% url 'about' as about_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}
{% url 'messaging:messages' as messages_url %}


<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>Spark Dating App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/SparkDatingLogo.ico' %}" />

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!--  jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column h-100 main-bg">

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
        <a class="navbar-brand fw-bold" href="{% url 'home' %}">
            <img src="{% static 'images/SparkDatingText.png' %}" alt="Spark Dating Logo" class="img-fluid" style="max-width: 100px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page"
                       href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/my-profile/' %}active{% endif %}" href="{% url 'my_profile' %}">My Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/messaging/matches/' %}active{% endif %}" href="{% url 'messaging:match_list' %}">Messages</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page" href="{% url 'account_logout' %}">Logout</a>
                </li>


                {% else %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
                       href="{% url 'account_signup' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page" href="{% url 'account_login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            <p class="text-end m-3">You are logged in as {{ user }}</p>
            {% else %}
            <p class="text-end m-3">You are not logged in</p>
            {% endif %}
            <span class="navbar-text text-muted" style="color: var(--primary-color);">
                    Find your match
                </span>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<main class="flex-shrink-0 main-bg">
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
</main>

<!-- Footer -->
<footer class="footer mt-auto py-3 dark-bg">
    {% block copyright %}
    <p class="m-0 text-center text-white">Spark Dating App © 2024</p>
    {% endblock copyright %}
    <p class="m-0 text-center text-white">Follow us:
        <a href="https://www.linkedin.com/in/vitor-barbosa-0912121b9/" target="_blank">
            <i class="fab fa-linkedin ms-3"></i>
        </a>
        <a href="https://github.com/VitorBarbosaDev" target="_blank">
            <i class="fab fa-github-square ms-3"></i>
        </a>

    </p>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
</script>
</body>

</html>